### ISSUE TITLE
Wildcards and "in" not working with integers

### ISSUE THREAD

**Issue by Tee88** [skaterdav85/validatorjs#398]
I am creating a rule for some object that I need to validate. The validation works fine when I use this syntax
`"someArray.*.parentProp.childProp": ["required", "integer"]`

However, when I add "in" with integer values I get the TypeError shown bellow.

`"someArray.*.parentPro.childProp": ["required", "integer", { in: [0, 1, 2, 3] }]`

```
TypeError: path2.indexOf is not a function

      3 | export default function validate(data, rules, customErrors) {
      4 |   const validatorCustomErrors = customErrors || {};
    > 5 |   const validator = new Validator(data, rules, validatorCustomErrors);
        |                     ^
      6 |   return validator;
      7 | }
      8 | 

      at services/devices-api/node_modules/validatorjs/src/validator.js:299:25
          at Array.forEach (<anonymous>)
      at Validator._replaceWildCards (services/devices-api/node_modules/validatorjs/src/validator.js:295:10)
      at Validator._parseRulesDefault (services/devices-api/node_modules/validatorjs/src/validator.js:275:27)
      at Validator._parseRulesCheck (services/devices-api/node_modules/validatorjs/src/validator.js:244:12)
      at Validator._parsedRulesRecurse (services/devices-api/node_modules/validatorjs/src/validator.js:256:14)
      at Validator._parseRulesCheck (services/devices-api/node_modules/validatorjs/src/validator.js:242:12)
      at Validator._parseRules (services/devices-api/node_modules/validatorjs/src/validator.js:233:12)
      at new Validator (services/devices-api/node_modules/validatorjs/src/validator.js:19:21)
      at validate (services/devices-api/src/libs/validator-lib.js:5:21)
```

**Comment by mikeerickson** [comment]
Hello

I believe you have the rule definition incorrect, it should be in formatted as a string, such as

```
"someArray.*.parentPro.childProp": ["required", "integer", "in:0,1,2,3" }]
```

Please adjust your code accordingly and see how this goes for you.

Mike
