### ISSUE TITLE
Validator.useLang('pt_BR') Error

### ISSUE THREAD

**Issue by densyy** [skaterdav85/validatorjs#406]
Hello people!

I'm getting this error message on the console:

```
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Messages._getAttributeName (/.../node_modules/validatorjs/src/messages.js:52:41)
    at Messages._replacePlaceholders (/.../node_modules/validatorjs/src/messages.js:136:27)
    at Messages.render (/.../node_modules/validatorjs/src/messages.js:88:22)
    at Validator._addFailure (/.../node_modules/validatorjs/src/validator.js:151:29)
    at Validator.check (/.../node_modules/validatorjs/src/validator.js:73:16)
    at Validator.fails (/.../node_modules/validatorjs/src/validator.js:511:18)
```

The problem only happens when Lang is defined as pt_BR
Code below:

```
const Validator = require('validatorjs')

exports.login = async (req, res, next) => {
  const { body } = req

  const rules = {
    email: 'required|string|email|max:100',
    senha: 'required|string|min:6|max:100'
  }

  Validator.useLang('pt_BR')
  const validation = new Validator(body, rules)
  // ...
}
```

My setup:
```
Node: v12.19.0
Npm: 6.14.8
OS: Manjaro Linux x86_64
Kernel: 5.10.7-3-MANJARO
```

**Comment by densyy** [comment]
Fixed just adding "attributes" property to the pt_BR.js file

```
attributes: {},
```

```
alpha_dash: 'O campo :attribute deve conter apenas letras, números e traços.',
alpha_num: 'O campo :attribute deve conter apenas letras e números .',
attributes: {},
array: 'O campo :attribute deve conter um array.',
before: 'O campo :attribute deve conter uma data anterior a :date.',
```

**Comment by mikeerickson** [comment]
Thank you for the report, this has also already been cured in the v3.5 upgrade I am work on
